# Tailscale sidecars whose serve.json is generated by nix.
#
# Every app in stacks/homelab pairs with a `ts-<name>` tailscale/tailscale
# container (hostname = tailnet name, HTTPS via TS_SERVE_CONFIG). An app that
# shares its sidecar's network namespace (`network_mode: service:ts-<name>`)
# binds nothing on the host and the firewall is untouched: the tailnet is the
# whole boundary, so apps with a login screen have it turned OFF in compose.
#
# Declaring a sidecar here does two things:
#   1. renders /etc/ts-<name>/serve.json, which the compose file bind-mounts
#      read-only at /config/serve.json;
#   2. unless `gatus = null`, adds an HTTPS check of the tailnet name to
#      gatus.nix, so DNS, the sidecar, TLS and the app are polled together.
#
# Both serve.json stanzas are required (docs/NIXOS-INFRA.md gotchas):
# TCP.443.HTTPS makes the sidecar terminate TLS with the tailnet cert, Web
# proxies to the app. Editing a rendered serve.json needs
# `docker restart ts-<name>` afterwards: compose does not recreate a
# container for a bind mount's contents.
#
# Adding an app: compose services (ts-<name> + app) in
# stacks/homelab/docker-compose.yml, one entry below, deploy. Removing:
# delete both, deploy (--remove-orphans removes the containers), then
# delete /srv/homelab/<app> and /srv/homelab/ts-<name> (the sidecar's tailnet
# identity — also remove the node in the Tailscale admin console).
#
# The older sidecars (budget, homepage, ntfy, adguard, librespeed, metube)
# still carry hand-made serve.json under /srv/homelab/ts-<name>/config;
# moving one here means also switching its compose volume to
# /etc/ts-<name>/serve.json.
{
  config,
  lib,
  ...
}: let
  cfg = config.homelab.sidecars;
in {
  options.homelab.sidecars = lib.mkOption {
    default = {};
    description = "Tailscale sidecars with nix-rendered serve.json, keyed by tailnet name.";
    type = lib.types.attrsOf (lib.types.submodule ({name, ...}: {
      options = {
        upstream = lib.mkOption {
          type = lib.types.str;
          example = "http://127.0.0.1:8080";
          description = "Where the sidecar proxies to. 127.0.0.1 when the app shares its namespace; host.docker.internal for a native service on the VM.";
        };
        gatus = lib.mkOption {
          type = lib.types.nullOr lib.types.str;
          default = name;
          description = "Gatus endpoint name for the https://<name>.jaguar-duckbill.ts.net check, or null to skip monitoring.";
        };
        conditions = lib.mkOption {
          type = lib.types.listOf lib.types.str;
          default = [];
          description = "Extra Gatus conditions on top of the 2xx check.";
        };
      };
    }));
  };

  config.environment.etc =
    lib.mapAttrs' (
      name: sidecar:
        lib.nameValuePair "ts-${name}/serve.json" {
          text = builtins.toJSON {
            TCP."443".HTTPS = true;
            Web."\${TS_CERT_DOMAIN}:443".Handlers."/".Proxy = sidecar.upstream;
          };
        }
    )
    cfg;
}
