services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_COUNTRIES=United States
      - FIREWALL_OUTBOUND_SUBNETS=192.168.0.0/16,172.16.0.0/12,10.0.0.0/8
      - TZ=America/Chicago
      # DNS fixes
      - DOT=off
      - DNS_ADDRESS=127.0.0.11
      - BLOCK_MALICIOUS=off
      # Completely disable healthcheck
      - HEALTH_VPN_DURATION_INITIAL=999h
      - HEALTH_VPN_DURATION_ADDITION=999h
    ports:
      # qBittorrent ports
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
      # Prowlarr port (if you want it through VPN)
      - 9696:9696
    volumes:
      - /mnt/tank/appdata/gluetun:/gluetun
    restart: unless-stopped
    networks:
      - arr-network

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=1002
      - TZ=America/Chicago
      - WEBUI_PORT=8081
      - TORRENTING_PORT=6881
    volumes:
      - /mnt/tank/appdata/qbittorrent/config:/config
      - /mnt/storage/downloads:/downloads
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=1002
      - TZ=America/Chicago
    volumes:
      - /mnt/storage/media/shows:/tv
      - /mnt/tank/appdata/sonarr/config:/config
      - /mnt/storage/downloads:/downloads
    ports:
      - 8989:8989
      - 9897:9897
    restart: unless-stopped
    networks:
      - arr-network

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1001
      - PGID=1002
      - TZ=America/Chicago
    volumes:
      - /mnt/tank/appdata/prowlarr/config:/config
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

networks:
  arr-network:
    driver: bridge
